case erlang:function_exported(rebar3, main, 1) of
    true ->
        CONFIG;
    false ->
        {value, {deps, Deps}, _} = lists:keytake(deps, 1, CONFIG),
        {value, {director, DirectorTag}, _} = lists:keytake(director, 1, Deps),
        DirectorLink = "https://github.com/pouriya-jahanbakhsh/director.git",
        Director = {director, ".*", {git, DirectorLink, {tag, DirectorTag}}},
        [{deps, [Director]}|CONFIG]
end.